### ISSUE TITLE
Django 4.2 removes is_summary from Query.add_annotation()

### ISSUE THREAD

**Issue by ShaheedHaque** [W1ldPo1nter/django-queryable-properties#8]
Hi,

As per the [release notes](https://docs.djangoproject.com/en/4.2/releases/4.2/#miscellaneous), Django 4.2 removes is_summary from Query.add_annotation() which causes this line to error out:

https://github.com/W1ldPo1nter/django-queryable-properties/blob/7c7f3229f421f90464dcffae306c97ad69233478/queryable_properties/query.py#L105

I'm afraid I'm not knowledgeable enough to suggest a workaround.

**Comment by W1ldPo1nter** [comment]
It's [already fixed](https://github.com/W1ldPo1nter/django-queryable-properties/commit/4b0cfd0ae41c3954e83f8e6f334f9bb56b10cdbd) in the respective feature branch.

I'll try to release a new version including the Django 4.2 support soon.

**Comment by ShaheedHaque** [comment]
Apologies for not thinking to check the branches!

**Comment by ShaheedHaque** [comment]
BTW, I'll ask here rather than open another issue: this is a brilliant library. Have you considered trying to get it included with Django proper?

**Comment by W1ldPo1nter** [comment]
Version 1.8.4, which adds support for Django 4.2, is now available on PyPI.

> Have you considered trying to get it included with Django proper? I'm thinking about it along the lines of general support for computed columns, i.e. pushed down to the dB if it supports it.

I haven't yet, really. Although it would probably be quite nice if Django supported something like this out of the box and the whole thing could be implemented in easier ways since *django-queryable-properties* has to perform quite some workarounds to integrate seamlessly. However, I guess trying to get it integrated would be a somewhat lengthy process and my time is somewhat limited (at the moment at least). So... I might consider it whenever I get to a point where I have enough time to invest.

**Comment by ShaheedHaque** [comment]
I have verified that 1.8.4 works just fine. Thanks for the quick fix (and the software!).
